data:
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXN0b3JhZ2VhY2Nwcm9qZWN0MjtBY2NvdW50S2V5PXlrRTgrcS95K1kwMzRuYTNkbkNBZEJYS01NOFZNb2hFWlU5SDYvQmNqSG8rb0ZxY3lsOWhnMlpjcmlKZllYdjkvaitWL3FRNGljSnMrQVN0ZGY5QkhRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  FUNCTIONS_EXTENSION_VERSION: fjM=
  WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW5laWdoYm9ybHlhcHByZzgwMWU7QWNjb3VudEtleT1ITTNiTnVPR25lMEJ5enl0UmpJT2NDZ1cxS2lnQ2xjYmozY1Q3S2lpQlJvK0R6SThjL1ZCaGdNUWIxeUc2azVMRFhmRDBtL0RhRnhZK0FTdDFGS0xldz09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  WEBSITE_CONTENTSHARE: bmVpZ2hib3JseWZ1bmN0aW9uYXBwODkzOA==
  mongodbconnection: bW9uZ29kYjovL21vbmdvZGJuZWlnaGJvcmx5YXBwOk1ZR3hKbk02a1JiSnZ0YjhIUVV0VWloTXVlRHdlaXFGa3VnV3lOeXlxMmFQUWJKSDV0ZVVBU0tic0ExQ2lpRm0zN0xseEsya2pqYnZBQ0RiSTRqWFZ3PT1AbW9uZ29kYm5laWdoYm9ybHlhcHAubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmV0cnl3cml0ZXM9ZmFsc2UmcmVwbGljYVNldD1nbG9iYWxkYiZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUBtb25nb2RibmVpZ2hib3JseWFwcEA=
  AzureWebJobs.HttpTrigger1.Disabled: dHJ1ZQ==
apiVersion: v1
kind: Secret
metadata:
  name: neighborlyappcluster11
---
data:
  host.master: R054aTNRRlA4Z3VwRzFKeU9kWHIzS2wyOElkUE1PN2NoR191TzgzZ2VJZHRBekZ1cEZtNGpnPT0=
  host.function.default: a1VxOXh5MEtsd1dadUZVS2VYWVhLSzNJX0JDYnZNTDNPQUxDZGhpcDlKWlRBekZ1WVVkS09RPT0=
  host.systemKey.default: VW0wTHVYb0lIajJ6RnBaLXVpV3RtZnFSTGxtQmpfX0pGamJvSFpSbmlmRUFBekZ1eUQ4dzZBPT0=
  functions.createadvertisement.default: NzBpMTF5bTd6SHpvUGFRODZLV1haSGt4MXV3andualVEaUlJOGNuU3NMeklBekZ1czBRdGZBPT0=
  functions.deleteadvertisement.default: OWhrZVMwbFpsMjhfT0FGYUFqU1JfTVpxZGpnRWJSMG9sdDRKUkRmVTFaNG9BekZ1clJuRWlRPT0=
  functions.getadvertisement.default: aEFrR2lBbzExZEJBYnM3VU1SX3laOTBIMEFVX2VtQmJsVVMwaThnd2JlaUNBekZ1ekJKWWV3PT0=
  functions.getadvertisements.default: ZE1sNkE4MFRPckN5NVBvQUdxT0JtYlg0YWdvQk82a3NIb2FSSDVIV1Y2RHVBekZ1bWpWbF9nPT0=
  functions.getpost.default: VEY3cm1IM0VscTJTanJnZmR1VlN6MF9ranlGSmg5eUZkWmZZUmhTRFV5N0lBekZ1dWg4ZjdBPT0=
  functions.getposts.default: WkU0S2tyRGRERG9KZmxUQVRGYi0yYlJhek9YcC05UjFYN19CdlFBMFFSNlJBekZ1R1I2cmZRPT0=
  functions.updateadvertisement.default: NEtyUVJvZVl3RXVhd1NlUGNobUVoTGdkX2VqQnlxZWhidlhtX1BiaEw3RDdBekZ1S1ZiTlFRPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-neighborlyappcluster11
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neighborlyappcluster11-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: neighborlyappcluster11-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neighborlyappcluster11-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: neighborlyappcluster11-http
spec:
  selector:
    app: neighborlyappcluster11-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlyappcluster11-http
  labels:
    app: neighborlyappcluster11-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborlyappcluster11-http
  template:
    metadata:
      labels:
        app: neighborlyappcluster11-http
    spec:
      containers:
      - name: neighborlyappcluster11-http
        image: neighborlyappcontainer.azurecr.io/neighborlyapi:v1
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-neighborlyappcluster11
        envFrom:
        - secretRef:
            name: neighborlyappcluster11
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlyappcluster11-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlyappcluster11
  labels:
    app: neighborlyappcluster11
spec:
  selector:
    matchLabels:
      app: neighborlyappcluster11
  template:
    metadata:
      labels:
        app: neighborlyappcluster11
    spec:
      containers:
      - name: neighborlyappcluster11
        image: neighborlyappcontainer.azurecr.io/neighborlyapi:v1
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: neighborlyappcluster11
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlyappcluster11-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neighborlyappcluster11
  labels: {}
spec:
  scaleTargetRef:
    name: neighborlyappcluster11
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

